name: Validation

on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ '*' ]
  workflow_dispatch:

jobs:
  validation:
    uses: JeffersonLab/clas12-validation/.github/workflows/ci.yml@gemc-matrix
    with:
      gemc_version: build
      config_file_versions: >-
        {
          "coatjava": "latest",
          "gemc":     "dev"
        }
      git_upstream: >-
        {
          "clas12-config": { "fork": "JeffersonLab/clas12-config", "ref": "dev" }
        }
