name: Validation

on:
  push:
    branches:
      - '*'
    tags: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validation:
    uses: JeffersonLab/clas12-validation/.github/workflows/ci.yml@main
    with:
      num_events: 500
      gemc_version: build
      config_file_versions: >-
        {
          "coatjava": "latest",
          "gemc":     "dev"
        }
      git_upstream: >-
        {
          "clas12-config": { "fork": "JeffersonLab/clas12-config", "ref": "dev" },
          "coatjava":      { "fork": "JeffersonLab/coatjava",      "ref": "" }
        }

